### ISSUE TITLE
Container sometimes not HUP'd

### ISSUE THREAD

**Issue by csmith** [csmith/Dotege#4]
@greboid has issues where the haproxy container sometimes doesn't get HUP'd after a config change.

I think we got as far as determining that Dotege didn't see the haproxy container as running for some reason - possibly because of a race condition when they both start together?

@greboid - can you paste dotege logs next time you catch it happening?

**Comment by greboid** [comment]
Log files provided in private

**Comment by csmith** [comment]
We've found and fixed two issues:

1) We were referencing containers by name, but these actually aren't unique in certain scenarios where containers are being restarted/updated - the new container spins up with the same name, then the old container gets destroyed; for a moment they both exist. Docker handles this by appending a short ID to the name to disambiguate them. Dotege now tracks by ID instead.

2) There was some race condition with listing containers after streaming events - when the haproxy container came up at the same time (e.g. with docker-compose) it somehow fell through the gaps. There doesn't seem to be a way to fix this within the limitations of the Docker API, so we now also refresh after a short delay. As the containers are indexed by ID now this is mostly a no-op, unless one of the containers was missed the first time.

**Comment by greboid** [comment]
Haven't had the issue since 1 + 2 above were fixed so probably good now
